language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false

matrix:
  - PYTHON=""

matrix:
  allow_failures:
    - julia: nightly

coveralls: true

before_install:
  - julia -e 'import Pkg; Pkg.pkg"add https://github.com/anowacki/Geodesics.jl"'
