language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false

matrix:
  - PYTHON=""

matrix:
  allow_failures:
    - julia: nightly

# Coverage submission currently broken due to
#     https://github.com/JuliaWeb/MbedTLS.jl/issues/193
# coveralls: true

before_install:
  - julia -e 'import Pkg; Pkg.pkg"add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/SAC.jl"'
