language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'ENV["PYTHON"] = "";
                                    import Pkg;
                                    Pkg.pkg"add https://github.com/anowacki/TauPy.jl https://github.com/anowacki/SeisTau.jl"'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

before_install:
  - julia -e 'import Pkg; Pkg.pkg"add https://github.com/anowacki/Geodesics.jl"'
